### ISSUE TITLE
上下バナーの文言入れ替え・追加

### ISSUE THREAD

**Issue by CiXWada** [hlrrr0/insyokujin#4]
【上バナー】
「飲食人研究所」→「飲食人大学研究所」に変更
【下バナー】
「飲食人大学研究所」を追加

（バナー以外の部分でももし箇所があれば、「飲食人研究所」→「飲食人大学研究所」に変更しておいてほしいです）

**Comment by CiXWada** [comment]
【上バナー】
「飲食人研究所」→「飲食人大学研究所」に変更
<img width="1369" alt="スクリーンショット 2024-05-01 19 28 14" src="https://github.com/hlrrr0/insyokujin/assets/167155104/1f336b7f-4b7d-4935-a6c6-1e87dc44c962">


【下バナー】
「飲食人大学研究所」を追加
<img width="1339" alt="スクリーンショット 2024-05-01 19 28 47" src="https://github.com/hlrrr0/insyokujin/assets/167155104/240a53a5-43e0-4208-ba18-a59bc65a648a">

**Comment by hlrrr0** [comment]
![スクリーンショット 2024-05-08 10 48 08](https://github.com/hlrrr0/insyokujin/assets/13173823/16f9b558-ae6f-4e7f-b449-dc5773deef54)
![スクリーンショット 2024-05-08 10 48 15](https://github.com/hlrrr0/insyokujin/assets/13173823/dafd282e-fe85-4d1e-a513-9540f91560e5)
対応完了
