### ISSUE TITLE
スライダー画像差し替え＋削除

### ISSUE THREAD

**Issue by CiXWada** [hlrrr0/insyokujin#5]
TOPページのスライダー
【差し替え】
・東京校限定 握り体験会→新しい画像
![HP　スライダー (2)](https://github.com/hlrrr0/insyokujin/assets/167155104/c5b499e3-00e0-45df-8496-9bc1367aabd7)
（[体験会フォームへリンク](https://insyokujin.ac/experience-session/)）

【削除】
・淡路島校限定 握り体験会＆交流会

**Comment by hlrrr0** [comment]
![スクリーンショット 2024-05-08 10 45 57](https://github.com/hlrrr0/insyokujin/assets/13173823/7116c11a-d383-4100-8a36-687028b20831)
対応完了
